### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_this.listeners[columnId][event]'

### ISSUE THREAD

**Issue by blindvalentine** [bear-junior/react-native-draganddrop-board#19]
Hi, I'm experiencing the following error 

TypeError: undefined is not an object (evaluating '_this.listeners[columnId][event]'

whenever I drag an item away from its initial position. What does this error refer to? I tried logging the listeners object within the BoardRepository component and it returns an empty object. Thanks in advance!
<img width="393" alt="Screenshot 2020-10-20 at 11 43 00 PM" src="https://user-images.githubusercontent.com/47374333/96610269-03e9a800-132e-11eb-87c8-561f21dfcd3f.png">

**Comment by TacticCoder** [comment]
Hey,
can you please attach your code and the Tech stack?

**Comment by tomasiturralde** [comment]
Hi, i'm having the same issue as blindvalentine. I'm using the basic example given on the readme, and my react native version is 0.62.2. Is there anything i'm missing that should be added to the basic example to make it work?

Edit to add: from what i've been testing, the problem seems to be (at least in my case) with using a state hook. I commented every piece of code besides the basic example, and then uncommented piece by piece to see what was generating the error. The result i arrived to was that when i call the setter method for the state hook, something is happening that is breaking the board. For reference this is the code that, when fully uncommented, break the board and generates the error shown on the original post (at least in my case, that is what generates this).
![image](https://user-images.githubusercontent.com/22356960/97095751-cb054800-1639-11eb-94b7-5ad79c7c74c3.png)


Second edit: I tried using a class instead of a functional component, same result, when i call setState, that makes the board break

**Comment by ariesbrylle-bms** [comment]
Same issue here.

**Comment by ariesbrylle-bms** [comment]
I was able to solve the problem. The problem occurs once the board is loaded then an update in the data happens.

Here's how I updated my data.

`
useEffect(() => {
    boardRepository.updateData(boardData);
}, [boardData]);

let boardRepository = new BoardRepository([]);
`

**Comment by TacticCoder** [comment]
Great job, this method is partly mentioned in the readme. Closed for now.

**Comment by ariesbrylle-bms** [comment]
Re-opening this issue. When I fixed the problem, this problem occurs -- https://github.com/bear-junior/react-native-draganddrop-board/issues/28

**Comment by ariesbrylle-bms** [comment]
Were you able to fix the issue @tomasiturralde @blindvalentine ?

**Comment by ariesbrylle-bms** [comment]
![image](https://user-images.githubusercontent.com/22163768/105568998-dcfda080-5d78-11eb-893b-18a9a63bb586.png)

**Comment by Luke-Mueller** [comment]
Has anyone seen any progress on this issue?
